# syntax=docker/dockerfile:1.7

# Generated by service-docker-scaffold. Source mode is the default because it
# produces a Linux binary for Docker's target platform instead of copying a
# host-native executable into the image.
#
# Substitutions:
#   1.26.1         exact Go toolchain version inferred from go.mod
#   ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.53 image supplying the grpc_health_probe binary
#   alpine:3.24      final runtime base image
#   .         service directory relative to the Docker build context
#         service path prefix relative to build context, or empty
#   ./cmd/server         main package passed to go build
#   user-service        output binary name
#   19094        grpcx gRPC listen port
#   18084          optional grpc-gateway listen port
#   config.example.yaml      non-secret config template copied as /app/config.yaml

ARG GO_VERSION=1.26.1
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-bookworm AS builder

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
# Go module proxy. Default is Go's standard public proxy; override with
# --build-arg GOPROXY=https://goproxy.cn,direct (or the GOPROXY env var, which
# compose build.args wires through) when proxy.golang.org is unreachable.
ARG GOPROXY=https://proxy.golang.org,direct

WORKDIR /src
ENV GOTOOLCHAIN=local
ENV GOPROXY=$GOPROXY

# Bind the build context read-only so standalone modules and monorepos with
# local replace directives use the same build. Module and compiler caches stay
# outside that mount and remain reusable across builds. The builder runs on
# BUILDPLATFORM while the Go compiler targets TARGETPLATFORM without QEMU.
RUN --mount=type=bind,source=.,target=/workspace \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    set -eu; \
    if [ "${TARGETOS}" != "linux" ]; then \
      echo "unsupported target OS: ${TARGETOS}; the runtime image is Linux" >&2; \
      exit 1; \
    fi; \
    case "${TARGETARCH}/${TARGETVARIANT}" in \
      amd64/) ;; \
      amd64/v1|amd64/v2|amd64/v3|amd64/v4) export GOAMD64="${TARGETVARIANT}" ;; \
      arm/|arm/v7) export GOARM=7 ;; \
      arm64/|arm64/v8|ppc64le/|s390x/) ;; \
      *) echo "unsupported target platform: ${TARGETPLATFORM}" >&2; exit 1 ;; \
    esac; \
    mkdir -p /out; \
    cd /workspace/.; \
    CGO_ENABLED=0 GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" \
      go build \
        -mod=readonly \
        -trimpath \
        -buildvcs=false \
        -ldflags="-s -w -buildid=" \
        -o /out/user-service \
        ./cmd/server

FROM ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.53 AS grpc-health-probe

FROM alpine:3.24
RUN apk add --no-cache ca-certificates tzdata \
    && adduser -D -u 10001 appuser

WORKDIR /app
COPY --from=builder /out/user-service /app/user-service
COPY --from=grpc-health-probe /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
COPY config.example.yaml /app/config.yaml

USER appuser
EXPOSE 19094
EXPOSE 18084
ENTRYPOINT ["/app/user-service"]
